### ISSUE TITLE
int / boolean are written as strings into the output

### ISSUE THREAD

**Issue by blushingpenguin** [jimmycuadra/ktmpl#3]
foo.yaml:
```yaml
kind: Template
apiVersion: v1
objects:
  - kind: Deployment
    apiVersion: apps/v1
    spec:
      replicas: $(REPLICAS)
parameters:
  - name: "REPLICAS"
    description: "number of pods"
    required: true
    value: 1
    parameterType: "bool"
```
ktmpl foo.yaml
```yaml
---
kind: Deployment
apiVersion: apps/v1
spec:
  replicas: "1"
```
this causes k8s to complain because replicas is a string not an integer.  A similar thing happens with boolean values.
